package com.cqut.dao;

import com.cqut.bean.Advice;

public interface AdviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    int insert(Advice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    int insertSelective(Advice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    Advice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    int updateByPrimaryKeySelective(Advice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(Advice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    int updateByPrimaryKey(Advice record);
}