package com.cqut.bean;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_number
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer orderNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.order_user_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer orderUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_name
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id_card_number
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer idCardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_telephone
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer userTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.user_email
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.flight_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer flightId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.type
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.shipping_type
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer shippingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.gate
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer gate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_number
     *
     * @return the value of order.order_number
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_number
     *
     * @param orderNumber the value for order.order_number
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setOrderNumber(Integer orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.order_user_id
     *
     * @return the value of order.order_user_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getOrderUserId() {
        return orderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.order_user_id
     *
     * @param orderUserId the value for order.order_user_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setOrderUserId(Integer orderUserId) {
        this.orderUserId = orderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_id
     *
     * @return the value of order.user_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_id
     *
     * @param userId the value for order.user_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_name
     *
     * @return the value of order.user_name
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_name
     *
     * @param userName the value for order.user_name
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id_card_number
     *
     * @return the value of order.id_card_number
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getIdCardNumber() {
        return idCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id_card_number
     *
     * @param idCardNumber the value for order.id_card_number
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setIdCardNumber(Integer idCardNumber) {
        this.idCardNumber = idCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_telephone
     *
     * @return the value of order.user_telephone
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getUserTelephone() {
        return userTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_telephone
     *
     * @param userTelephone the value for order.user_telephone
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setUserTelephone(Integer userTelephone) {
        this.userTelephone = userTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.user_email
     *
     * @return the value of order.user_email
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.user_email
     *
     * @param userEmail the value for order.user_email
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.flight_id
     *
     * @return the value of order.flight_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getFlightId() {
        return flightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.flight_id
     *
     * @param flightId the value for order.flight_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setFlightId(Integer flightId) {
        this.flightId = flightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.type
     *
     * @return the value of order.type
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.type
     *
     * @param type the value for order.type
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.shipping_type
     *
     * @return the value of order.shipping_type
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getShippingType() {
        return shippingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.shipping_type
     *
     * @param shippingType the value for order.shipping_type
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setShippingType(Integer shippingType) {
        this.shippingType = shippingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.gate
     *
     * @return the value of order.gate
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getGate() {
        return gate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.gate
     *
     * @param gate the value for order.gate
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setGate(Integer gate) {
        this.gate = gate;
    }
}