package com.cqut.bean;

import java.util.Date;

public class Advice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice.id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice.user_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice.create_date
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice.update_date
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice.create_user
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice.update_user
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advice.content
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice.id
     *
     * @return the value of advice.id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice.id
     *
     * @param id the value for advice.id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice.user_id
     *
     * @return the value of advice.user_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice.user_id
     *
     * @param userId the value for advice.user_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice.create_date
     *
     * @return the value of advice.create_date
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice.create_date
     *
     * @param createDate the value for advice.create_date
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice.update_date
     *
     * @return the value of advice.update_date
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice.update_date
     *
     * @param updateDate the value for advice.update_date
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice.create_user
     *
     * @return the value of advice.create_user
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice.create_user
     *
     * @param createUser the value for advice.create_user
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice.update_user
     *
     * @return the value of advice.update_user
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice.update_user
     *
     * @param updateUser the value for advice.update_user
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advice.content
     *
     * @return the value of advice.content
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advice.content
     *
     * @param content the value for advice.content
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}