package com.cqut.bean;

import java.util.Date;

public class AirBus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air_bus.id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air_bus.name
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air_bus.buy_time
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Date buyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air_bus.last_use_time
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Date lastUseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air_bus.capacity
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer capacity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air_bus.weight
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Float weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air_bus.oil_weight
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Float oilWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air_bus.power
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Float power;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air_bus.engine_amount
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer engineAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air_bus.length
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Float length;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air_bus.area
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Float area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column air_bus.height
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Float height;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_bus.id
     *
     * @return the value of air_bus.id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_bus.id
     *
     * @param id the value for air_bus.id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_bus.name
     *
     * @return the value of air_bus.name
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_bus.name
     *
     * @param name the value for air_bus.name
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_bus.buy_time
     *
     * @return the value of air_bus.buy_time
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Date getBuyTime() {
        return buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_bus.buy_time
     *
     * @param buyTime the value for air_bus.buy_time
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setBuyTime(Date buyTime) {
        this.buyTime = buyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_bus.last_use_time
     *
     * @return the value of air_bus.last_use_time
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Date getLastUseTime() {
        return lastUseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_bus.last_use_time
     *
     * @param lastUseTime the value for air_bus.last_use_time
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setLastUseTime(Date lastUseTime) {
        this.lastUseTime = lastUseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_bus.capacity
     *
     * @return the value of air_bus.capacity
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_bus.capacity
     *
     * @param capacity the value for air_bus.capacity
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_bus.weight
     *
     * @return the value of air_bus.weight
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Float getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_bus.weight
     *
     * @param weight the value for air_bus.weight
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setWeight(Float weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_bus.oil_weight
     *
     * @return the value of air_bus.oil_weight
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Float getOilWeight() {
        return oilWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_bus.oil_weight
     *
     * @param oilWeight the value for air_bus.oil_weight
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setOilWeight(Float oilWeight) {
        this.oilWeight = oilWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_bus.power
     *
     * @return the value of air_bus.power
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Float getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_bus.power
     *
     * @param power the value for air_bus.power
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setPower(Float power) {
        this.power = power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_bus.engine_amount
     *
     * @return the value of air_bus.engine_amount
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getEngineAmount() {
        return engineAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_bus.engine_amount
     *
     * @param engineAmount the value for air_bus.engine_amount
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setEngineAmount(Integer engineAmount) {
        this.engineAmount = engineAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_bus.length
     *
     * @return the value of air_bus.length
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Float getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_bus.length
     *
     * @param length the value for air_bus.length
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setLength(Float length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_bus.area
     *
     * @return the value of air_bus.area
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Float getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_bus.area
     *
     * @param area the value for air_bus.area
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setArea(Float area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column air_bus.height
     *
     * @return the value of air_bus.height
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Float getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column air_bus.height
     *
     * @param height the value for air_bus.height
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setHeight(Float height) {
        this.height = height;
    }
}