package com.cqut.bean;

import java.util.Date;

public class Flight {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.flight_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private String flightId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.begin
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private String begin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.end
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private String end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.start_time
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.reach_time
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Date reachTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.start_airport
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private String startAirport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.target_airport
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private String targetAirport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.runway
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer runway;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.runway
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private String airId;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.runway
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer firstClassCapacity;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flight.runway
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer touristCapacity;

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.id
     *
     * @return the value of flight.id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.id
     *
     * @param id the value for flight.id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.flight_id
     *
     * @return the value of flight.flight_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public String getFlightId() {
        return flightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.flight_id
     *
     * @param flightId the value for flight.flight_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setFlightId(String flightId) {
        this.flightId = flightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.begin
     *
     * @return the value of flight.begin
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public String getBegin() {
        return begin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.begin
     *
     * @param begin the value for flight.begin
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setBegin(String begin) {
        this.begin = begin == null ? null : begin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.end
     *
     * @return the value of flight.end
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public String getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.end
     *
     * @param end the value for flight.end
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setEnd(String end) {
        this.end = end == null ? null : end.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.start_time
     *
     * @return the value of flight.start_time
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.start_time
     *
     * @param startTime the value for flight.start_time
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.reach_time
     *
     * @return the value of flight.reach_time
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Date getReachTime() {
        return reachTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.reach_time
     *
     * @param reachTime the value for flight.reach_time
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setReachTime(Date reachTime) {
        this.reachTime = reachTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.start_airport
     *
     * @return the value of flight.start_airport
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public String getStartAirport() {
        return startAirport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.start_airport
     *
     * @param startAirport the value for flight.start_airport
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setStartAirport(String startAirport) {
        this.startAirport = startAirport == null ? null : startAirport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.target_airport
     *
     * @return the value of flight.target_airport
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public String getTargetAirport() {
        return targetAirport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.target_airport
     *
     * @param targetAirport the value for flight.target_airport
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setTargetAirport(String targetAirport) {
        this.targetAirport = targetAirport == null ? null : targetAirport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flight.runway
     *
     * @return the value of flight.runway
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getRunway() {
        return runway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flight.runway
     *
     * @param runway the value for flight.runway
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setRunway(Integer runway) {
        this.runway = runway;
    }
    
    public String getAirId() {
		return airId;
	}

	public void setAirId(String airId) {
		this.airId = airId;
	}

	public Integer getFirstClassCapacity() {
		return firstClassCapacity;
	}

	public void setFirstClassCapacity(Integer firstClassCapacity) {
		this.firstClassCapacity = firstClassCapacity;
	}

	public Integer getTouristCapacity() {
		return touristCapacity;
	}

	public void setTouristCapacity(Integer touristCapacity) {
		this.touristCapacity = touristCapacity;
	}
}