package com.cqut.bean;

public class Indent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.indent_number
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer indentNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.indent_user_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer indentUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.user_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.user_name
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.id_card_number
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer idCardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.user_telephone
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer userTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.user_email
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.flight_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer flightId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.type
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.shipping_type
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer shippingType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column indent.gate
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer gate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.id
     *
     * @return the value of indent.id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.id
     *
     * @param id the value for indent.id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.indent_number
     *
     * @return the value of indent.indent_number
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getIndentNumber() {
        return indentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.indent_number
     *
     * @param indentNumber the value for indent.indent_number
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setIndentNumber(Integer indentNumber) {
        this.indentNumber = indentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.indent_user_id
     *
     * @return the value of indent.indent_user_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getIndentUserId() {
        return indentUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.indent_user_id
     *
     * @param indentUserId the value for indent.indent_user_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setIndentUserId(Integer indentUserId) {
        this.indentUserId = indentUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.user_id
     *
     * @return the value of indent.user_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.user_id
     *
     * @param userId the value for indent.user_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.user_name
     *
     * @return the value of indent.user_name
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.user_name
     *
     * @param userName the value for indent.user_name
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.id_card_number
     *
     * @return the value of indent.id_card_number
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getIdCardNumber() {
        return idCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.id_card_number
     *
     * @param idCardNumber the value for indent.id_card_number
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setIdCardNumber(Integer idCardNumber) {
        this.idCardNumber = idCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.user_telephone
     *
     * @return the value of indent.user_telephone
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getUserTelephone() {
        return userTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.user_telephone
     *
     * @param userTelephone the value for indent.user_telephone
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setUserTelephone(Integer userTelephone) {
        this.userTelephone = userTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.user_email
     *
     * @return the value of indent.user_email
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.user_email
     *
     * @param userEmail the value for indent.user_email
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.flight_id
     *
     * @return the value of indent.flight_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getFlightId() {
        return flightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.flight_id
     *
     * @param flightId the value for indent.flight_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setFlightId(Integer flightId) {
        this.flightId = flightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.type
     *
     * @return the value of indent.type
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.type
     *
     * @param type the value for indent.type
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.shipping_type
     *
     * @return the value of indent.shipping_type
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getShippingType() {
        return shippingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.shipping_type
     *
     * @param shippingType the value for indent.shipping_type
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setShippingType(Integer shippingType) {
        this.shippingType = shippingType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column indent.gate
     *
     * @return the value of indent.gate
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getGate() {
        return gate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column indent.gate
     *
     * @param gate the value for indent.gate
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setGate(Integer gate) {
        this.gate = gate;
    }
}