package com.cqut.bean;

import java.util.Date;

public class Ticket {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.id
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.flight_id
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    private Integer flightId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.price
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.begin
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    private String begin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.end
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    private String end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.start_time
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.reach_time
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    private Date reachTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.start_airport
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    private String startAirport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.target_airport
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    private String targetAirport;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.id
     *
     * @return the value of ticket.id
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.id
     *
     * @param id the value for ticket.id
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.flight_id
     *
     * @return the value of ticket.flight_id
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    public Integer getFlightId() {
        return flightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.flight_id
     *
     * @param flightId the value for ticket.flight_id
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    public void setFlightId(Integer flightId) {
        this.flightId = flightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.price
     *
     * @return the value of ticket.price
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.price
     *
     * @param price the value for ticket.price
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.begin
     *
     * @return the value of ticket.begin
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    public String getBegin() {
        return begin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.begin
     *
     * @param begin the value for ticket.begin
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    public void setBegin(String begin) {
        this.begin = begin == null ? null : begin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.end
     *
     * @return the value of ticket.end
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    public String getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.end
     *
     * @param end the value for ticket.end
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    public void setEnd(String end) {
        this.end = end == null ? null : end.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.start_time
     *
     * @return the value of ticket.start_time
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.start_time
     *
     * @param startTime the value for ticket.start_time
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.reach_time
     *
     * @return the value of ticket.reach_time
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    public Date getReachTime() {
        return reachTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.reach_time
     *
     * @param reachTime the value for ticket.reach_time
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    public void setReachTime(Date reachTime) {
        this.reachTime = reachTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.start_airport
     *
     * @return the value of ticket.start_airport
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    public String getStartAirport() {
        return startAirport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.start_airport
     *
     * @param startAirport the value for ticket.start_airport
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    public void setStartAirport(String startAirport) {
        this.startAirport = startAirport == null ? null : startAirport.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.target_airport
     *
     * @return the value of ticket.target_airport
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    public String getTargetAirport() {
        return targetAirport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.target_airport
     *
     * @param targetAirport the value for ticket.target_airport
     *
     * @mbggenerated Sun Jul 24 11:09:28 CST 2016
     */
    public void setTargetAirport(String targetAirport) {
        this.targetAirport = targetAirport == null ? null : targetAirport.trim();
    }
}