package com.cqut.bean;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.to_user_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer toUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.from_user_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer fromUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.is_read
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer isRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.type
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_date
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.update_date
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_user
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.update_user
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.read_date
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Date readDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.to_user_id
     *
     * @return the value of message.to_user_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.to_user_id
     *
     * @param toUserId the value for message.to_user_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setToUserId(Integer toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.from_user_id
     *
     * @return the value of message.from_user_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.from_user_id
     *
     * @param fromUserId the value for message.from_user_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setFromUserId(Integer fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.is_read
     *
     * @return the value of message.is_read
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.is_read
     *
     * @param isRead the value for message.is_read
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setIsRead(Integer isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.type
     *
     * @return the value of message.type
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.type
     *
     * @param type the value for message.type
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_date
     *
     * @return the value of message.create_date
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_date
     *
     * @param createDate the value for message.create_date
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.update_date
     *
     * @return the value of message.update_date
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.update_date
     *
     * @param updateDate the value for message.update_date
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_user
     *
     * @return the value of message.create_user
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_user
     *
     * @param createUser the value for message.create_user
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.update_user
     *
     * @return the value of message.update_user
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.update_user
     *
     * @param updateUser the value for message.update_user
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.read_date
     *
     * @return the value of message.read_date
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Date getReadDate() {
        return readDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.read_date
     *
     * @param readDate the value for message.read_date
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setReadDate(Date readDate) {
        this.readDate = readDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}