package com.cqut.bean;

import java.util.Date;

public class ReplyAdvice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_advice.id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_advice.advice_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer adviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_advice.create_date
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_advice.update_date
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_advice.create_user
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_advice.update_user
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private Integer updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_advice.content
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_advice.id
     *
     * @return the value of reply_advice.id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_advice.id
     *
     * @param id the value for reply_advice.id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_advice.advice_id
     *
     * @return the value of reply_advice.advice_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getAdviceId() {
        return adviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_advice.advice_id
     *
     * @param adviceId the value for reply_advice.advice_id
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setAdviceId(Integer adviceId) {
        this.adviceId = adviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_advice.create_date
     *
     * @return the value of reply_advice.create_date
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_advice.create_date
     *
     * @param createDate the value for reply_advice.create_date
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_advice.update_date
     *
     * @return the value of reply_advice.update_date
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_advice.update_date
     *
     * @param updateDate the value for reply_advice.update_date
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_advice.create_user
     *
     * @return the value of reply_advice.create_user
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_advice.create_user
     *
     * @param createUser the value for reply_advice.create_user
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setCreateUser(Integer createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_advice.update_user
     *
     * @return the value of reply_advice.update_user
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public Integer getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_advice.update_user
     *
     * @param updateUser the value for reply_advice.update_user
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setUpdateUser(Integer updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_advice.content
     *
     * @return the value of reply_advice.content
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_advice.content
     *
     * @param content the value for reply_advice.content
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}