package com.cqut.dao;

import java.util.List;
import java.util.Map;

import com.cqut.bean.AirBus;


public interface AirBusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_bus
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    public Long getTotal(Map<String,Object> map);
    /**
	 * 查询客户集合
	 * @param map
	 * @return
	 */
	public List<AirBus> find(Map<String,Object> map);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_bus
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    int insert(AirBus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_bus
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    int insertSelective(AirBus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_bus
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    AirBus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_bus
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    int updateByPrimaryKeySelective(AirBus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table air_bus
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    int updateByPrimaryKey(AirBus record);

	
}