package com.cqut.dao;

import com.cqut.bean.ReplyAdvice;

public interface ReplyAdviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply_advice
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply_advice
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    int insert(ReplyAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply_advice
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    int insertSelective(ReplyAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply_advice
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    ReplyAdvice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply_advice
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    int updateByPrimaryKeySelective(ReplyAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply_advice
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(ReplyAdvice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply_advice
     *
     * @mbggenerated Sun Jul 24 13:40:49 CST 2016
     */
    int updateByPrimaryKey(ReplyAdvice record);
}